/**
 * Builds the embedded editor document.
 *
 * Finite and offline: one esbuild run over the browser entry, one stylesheet read, one HTML
 * composition, one file written. It downloads nothing, watches nothing, and starts no service.
 * esbuild's platform binary arrives through its optional platform dependency, never through an
 * install script, and a missing or mismatched binary fails here with a clear message.
 *
 * It writes only on success. The output is git-ignored, so a clean checkout has nothing to fall back
 * on and stale output can never be mistaken for a successful build.
 */

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { CONTENT_SCHEMA_VERSION } from '@raphael/content';
import * as esbuild from 'esbuild';

import { EDITOR_BRIDGE_VERSION } from '../src/modules/editor/bridge.ts';
import {
  PAYLOAD_DIGEST_TOKEN,
  buildEditorDocument,
} from '../src/modules/editor/webview/template.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const webview = path.join(here, '..', 'src', 'modules', 'editor', 'webview');
const generated = path.join(here, '..', 'src', 'modules', 'editor', 'generated');

const fail = (message) => {
  process.stderr.write(`build-editor: ${message}\n`);
  process.exit(1);
};

/**
 * Module resolution is ordinary workspace package resolution against `@raphael/content`'s exports,
 * which is why the package must be built to `dist` first. No source aliases and no path mapping: the
 * editor consumes the package exactly the way any other consumer does.
 */
const bundle = async () => {
  const result = await esbuild.build({
    entryPoints: [path.join(webview, 'entry.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    sourcemap: false,
    legalComments: 'inline',
    write: false,
    metafile: true,
    absWorkingDir: path.join(here, '..'),
  });
  const output = result.outputFiles?.[0];
  if (output === undefined) fail('esbuild produced no output');
  return { code: output.text, metafile: result.metafile };
};

const main = async () => {
  const { code, metafile } = await bundle();
  const css = await readFile(path.join(webview, 'editor.css'), 'utf8');
  const html = buildEditorDocument({ css, bundle: code });

  // Escaping happens in the template; this proves it did not corrupt the program. An inline script
  // that no longer parses would otherwise ship as a document that starts and does nothing.
  const embedded = html.slice(
    html.lastIndexOf('<script>') + '<script>'.length,
    html.lastIndexOf('</script>'),
  );
  try {
    esbuild.transformSync(embedded, { loader: 'js' });
  } catch (error) {
    fail(`the embedded script does not parse after escaping: ${String(error)}`);
  }

  if (!html.includes(PAYLOAD_DIGEST_TOKEN)) fail('the digest placeholder is missing');

  // Over the document with the placeholder still in place: a stable input that covers the markup,
  // the stylesheet and the bundle, and cannot contain its own hash.
  const digest = `sha256-${createHash('sha256').update(html, 'utf8').digest('base64')}`;
  const document = html.replaceAll(PAYLOAD_DIGEST_TOKEN, digest);

  const literal = JSON.stringify(document)
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');

  const module = [
    '// Generated by scripts/build-editor.mjs. Do not edit; do not commit.',
    '',
    "import type { EditorStamp } from '../bridge.ts';",
    '',
    `export const EDITOR_DOCUMENT_HTML = ${literal};`,
    '',
    'export const EDITOR_DOCUMENT_STAMP: EditorStamp = {',
    `  bridgeVersion: ${EDITOR_BRIDGE_VERSION},`,
    `  contentSchemaVersion: ${CONTENT_SCHEMA_VERSION},`,
    `  payloadDigest: ${JSON.stringify(digest)},`,
    '};',
    '',
  ].join('\n');

  await mkdir(generated, { recursive: true });
  await writeFile(path.join(generated, 'document.ts'), module, 'utf8');

  const inputs = Object.keys(metafile?.inputs ?? {});
  process.stdout.write(
    `build-editor: ${inputs.length} modules, ${(document.length / 1024).toFixed(1)} KiB document, ${digest}\n`,
  );
};

await main().catch((error) => fail(String(error?.stack ?? error)));
